"""
Django settings for Engage project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y4z)*ji7^uopwgq#@u(5$2$51&6+mqrk5=02p4$$eppb6yhyms'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard',
    'social_django',
    'crispy_forms',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

# SOCIALACCOUNT_PROVIDERS = {
#    'google': {
#       'SCOPE': [
#          'profile',
#          'email',
#       ],
#       'AUTH_PARAMS': {
#          'access_type': 'online',
#       }
#    }
# }


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Engage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'Engage.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Social Media Sign-in
AUTHENTICATION_BACKENDS = [
    'social_core.backends.linkedin.LinkedinOAuth2',
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[BASE_DIR/"static"]

CRISPY_TEMPLATE_PACK = "bootstrap"  # for setting bootstrap for "Create Notes"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = 'signin'
LOGOUT_URL = 'signout'
LOGOUT_REDIRECT_URL = 'signin'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#  For LinkedIn
SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY = "78prjw7w4h3we7"        # Client ID
SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET = "VZ7vMq4lbIAihtWX"  # Client Secret

# For Facebook
SOCIAL_AUTH_FACEBOOK_KEY = "629023811622098"        # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = "8d88c3554fc1481edd8d59ea87678a7f"  # App Secret

# For Github
SOCIAL_AUTH_GITHUB_KEY = "de69e719d2715b323fc5"        # App ID
SOCIAL_AUTH_GITHUB_SECRET = "c428af6e53bc5fadaa4e34051f098587a8f567d5"  # App Secret

# SOCIAL_AUTH_GOOGLE_OAUTH_KEY = "147941173930-rnso0mgl6kj0spmsp3kdtp34hqjpadcq.apps.googleusercontent.com"        # App ID
# SOCIAL_AUTH_GOOGLE_OAUTH_SECRET = "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"  # App Secret

SITE_ID = 1
