# Generated by Django 3.2.9 on 2021-11-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Notes', 'verbose_name_plural': 'Notes'},
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='content',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='heading',
            new_name='title',
        ),
    ]
