# Generated by Django 3.2.9 on 2021-11-17 09:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_homewoek'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Homewoek',
            new_name='Homework',
        ),
    ]
