# Generated by Django 3.2.9 on 2021-11-25 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
